--21.2.17 실습문제

-- 3.
SELECT BOOK_NO "책번호", BOOK_NM "도서명"
FROM TB_BOOK
WHERE LENGTH(BOOK_NM) >= 25
ORDER BY 1;

-- 4.
SELECT WRITER_NM "이름" , OFFICE_TELNO "사무실 전화번호", 
       HOME_TELNO " 집 전화번호", MOBILE_NO "휴대폰 전화번호"
FROM TB_WRITER
WHERE MOBILE_NO LIKE '019%' AND WRITER_NM LIKE '김%'
ORDER BY 1;

-- 5.
SELECT COUNT(WRITER_NO) "작가(명)"
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE LIKE '옮김'

SELECT COUNT(WRITER_NM) "작가(명)"
FROM TB_BOOK_AUTHOR
JOIN TB_WRITER USING(WRITER_NO)
WHERE COMPOSE_TYPE LIKE '옮김';

-- 6. 
SELECT COMPOSE_TYPE ,COUNT(BOOK_NO)
FROM TB_BOOK_AUTHOR
GROUP BY COMPOSE_TYPE
HAVING COUNT(BOOK_NO) >= 300;

-- 7. 
SELECT BOOK_NM 도서명, ISSUE_DATE 발행일자, PUBLISHER_NM 출판사이름
FROM TB_BOOK 
ORDER BY ISSUE_DATE DESC;

-- 8. 보류
SELECT WRITER_NM "작가이름", COUNT(BOOK_NO) "권 수"
FROM TB_WRITER
JOIN TB_BOOK_AUTHOR USING(WRITER_NO);

-- 9. 누락??

-- 10.
CREATE TABLE TB_BOOK_TRANSLATOR(
    BOOK_NO VARCHAR2(20) CONSTRAINT FK_BOOK_TRANSLATOR_01 REFERENCE TB_BOOK,
    WRITER_NO VARCHAR2(20) CONSTRAINT FK_BOOK_TRANSLATOR_02 REFERENCE TB_WRITER,
    TRANS_LANG VARCHAR2(20),
    PRIMARY KEY(BOOK_NO, WRITER_NO) CONSTRAINT PK_BOOK_TRANSLATOR,
    FOREIGN KEY(BOOK_NO, WRITER_NO) REFEFENCE 
);

COMMENT ON COLUMN TB_BOOK_TRANSLATOR.BOOK_NO IS '도서번호';
COMMENT ON COLUMN TB_BOOK_TRANSLATOR.WRITER_NO IS '작가번호';
COMMENT ON COLUMN TB_BOOK_TRANSLATOR.TRANS_LANG IS '번역언어';






















