-- 21.02.02 실습문제

-- 1.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3.//
SELECT PROFESSOR_NAME 교수이름
     , (EXTRACT(YEAR FROM SYSDATE) - CONCAT(19,SUBSTR(PROFESSOR_SSN,1,2))) 나이    
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY PROFESSOR_NAME;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME,2) 교수이름
FROM TB_PROFESSOR;

-- 5. 
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)- CONCAT(19,SUBSTR(STUDENT_SSN,1,2)) > 19;

-- 6.//형변환
SELECT TO_CHAR(TO_DATE('2020/12/25'),'DAY')
FROM DUAL;

-- 7.//형변환
SELECT TO_DATE('99/10/11', 'YY/MM/DD')
     , TO_DATE('49/10/11', 'YY/MM/DD')
     , TO_DATE('99/10/11', 'RR/MM/DD')
     , TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;

-- 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ENTRANCE_DATE < '2000/01/01';
--쌤답) WHERE STUDENT_NO NOT LIKE 'A%'; --> 2000년도 이후 입학자들은 학번이 A로 시작

-- 9.
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10.
SELECT DEPARTMENT_NO 학과번호, COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12.
SELECT SUBSTR(TERM_NO,1,4) AS "년도", ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;

-- 13./
SELECT DEPARTMENT_NO AS "학과 번호", COUNT(DECODE(ABSENCE_YN,'Y',1,NULL)) AS "휴학생 수"    
-- *COUNT(DECODE(ABSENCE_YN,'Y',1,NULL)) 부연 설명 'Y'일 경우 COUNT(1)이 되어 카운팅됨
--                                                'Y'가 아닐경우 COUNT(NULL)되어 카운팅되지 않음
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 14.
SELECT STUDENT_NAME AS "동일이름", COUNT(*) AS "동명이인 수"
FROM TB_STUDENT 
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1;

-- 15. //
SELECT SUBSTR(TERM_NO,1,4) 년도
     , SUBSTR(TERM_NO,5,6) 학기
     , ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO
ORDER BY TERM_NO;









