-- 21.01.29 실습문제

-- 1. 별칭
SELECT DEPARTMENT_NAME AS "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

--2. 연결 연산자, 별칭
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

-- 3. 조건(AND)
SELECT STUDENT_NAME
--FROM  TB_DEPARTMENT, TB_STUDENT
FROM TB_STUDENT
WHERE --DEPARTMENT_NAME LIKE '국어국문학과';
        DEPARTMENT_NO = '001'
        AND SUBSTR(STUDENT_SSN,8,1) IN ('2', '4')
        AND ABSENCE_YN = 'Y';
        
-- 4. 조건(IN), 정렬(ORDER BY)
SELECT STUDENT_NAME 
FROM TB_STUDENT 
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC;

-- 5. BETWEEN AND
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30; 

-- 6. NULL
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7. NULL
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8. NULL
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 중복제외(DISTINCT)
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY CATEGORY ASC;

-- 10. 조건(LIKE)
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ENTRANCE_DATE LIKE '02%' AND  ABSENCE_YN = 'N' AND STUDENT_ADDRESS LIKE '전주%';